//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewNodeChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewNodeChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config connection String.
        /// </summary>
        internal static string LogConfigConnectionString {
            get {
                return ResourceManager.GetString("LogConfigConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogHostsFileContent.
        /// </summary>
        internal static string LogHostsFileContent {
            get {
                return ResourceManager.GetString("LogHostsFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogInstalledApps.
        /// </summary>
        internal static string LogInstalledApps {
            get {
                return ResourceManager.GetString("LogInstalledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogPortsAvailability.
        /// </summary>
        internal static string LogPortsAvailability {
            get {
                return ResourceManager.GetString("LogPortsAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string LogSite {
            get {
                return ResourceManager.GetString("LogSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogSqlAccess.
        /// </summary>
        internal static string LogSqlAccess {
            get {
                return ResourceManager.GetString("LogSqlAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogURLsHit.
        /// </summary>
        internal static string LogURLsHit {
            get {
                return ResourceManager.GetString("LogURLsHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogWebsitesInfo.
        /// </summary>
        internal static string LogWebsitesInfo {
            get {
                return ResourceManager.GetString("LogWebsitesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogWebsitesInfo IIS6.
        /// </summary>
        internal static string LogWebsitesInfoIIS6 {
            get {
                return ResourceManager.GetString("LogWebsitesInfoIIS6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogWebsitesInfo IIS7.
        /// </summary>
        internal static string LogWebsitesInfoIIS7 {
            get {
                return ResourceManager.GetString("LogWebsitesInfoIIS7", resourceCulture);
            }
        }
    }
}
